# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Daily update of data and charts

on:
  schedule:
      # Depends on csv file generated daily at 14:15-ish, run this at 14:17.
      # UTC is currently -1 wrt Europe/Stockholm (CEST).
      - cron: "17 13 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest
    - name: Install and check available locales
      run: |
        sudo locale-gen sv_SE
        sudo locale-gen sv_SE.UTF-8
        sudo update-locale 
        locale -a
    - name: Update data and charts
      run: |
        make all
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automatic update of data and charts
